# Correpsonds to the list of organisms with their files in the data/datasets folder.
# The data should be in following folder: data/datasets/{organism}, e.g. data/datasets/arabidopsis_thaliana
organisms:
  Arabidopsis thaliana: arabidopsis_thaliana
  Caenorhabditis elegans: caenorhabditis_elegans
  Danio rerio: danio_rerio
  Drosophila melanogaster: drosophila_melanogaster
  Homo sapiens: homo_sapiens
  Mus musculus: mus_musculus
  Saccharomyces cerevisiae: saccharomyces_cerevisiae